### ISSUE TITLE
Project needs animation styles included.

### ISSUE THREAD

**Issue by gunn** [mgcrea/angular-touch-nav#2]
At the very least for the default "animation-slide" transition. I have some css working and I'll create a pull-request soon.

Interestingly, in trying to experimenting with CSS I uncovered an odd bug - using the following styles modified from the angular-mobile-nav project, navigations result in the relevant ngViews never being removed i.e. 10 navigations results in 10+1 views sticking around in the dom. 

``` css
@keyframes slideInFromRight {
  0% { transform: translate3d(100%, 0, 0); }
  100% { transform: translate3d(0, 0, 0); }
}
@keyframes slideOutToRight {
  0% { transform: translate3d(0, 0, 0); }
  100% { transform: translate3d(100%, 0, 0); }
}
@keyframes slideInFromLeft {
  0% { transform: translate3d(-100%,0,0); }
  100% { transform: translate3d(0, 0, 0); }
}
@keyframes slideOutToLeft {
  0% { transform: translate3d(0,0,0); }
  100% { transform: translate3d(-100%, 0, 0); }
}

.animation-slide {
  animation-duration: 0.3s;
  animation-timing-function: ease;
}
.animation-slide.ng-enter {
  animation-name: slideInFromRight;
}
.animation-slide.ng-enter.ng-reverse {
  animation-name: slideOutToRight;
  transform: translate3d(100%, 0, 0);
}
.animation-slide.ng-leave {
  animation-name: slideOutToLeft;
  transform: translate3d(-100%, 0, 0);
}
.animation-slide.ng-leave.ng-reverse {
  animation-name: slideInFromLeft;
}
```
